_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "6": 4.53.1
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 4
checkpoint_path:
    value: ../../converted/olmo2_1b/model_and_optim
data_manifest:
    value: /ssd/karen/Titan_OLMo_core/src/scripts/train/anneal/fineweb_val.txt
device:
    value: cuda
eval_steps:
    value: 5000
model_type:
    value: olmo2_1b_baseline
sequence_length:
    value: 1024
use_sliding_window:
    value: true
window_size:
    value: 512
