name: Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  # TODO: disabled for now because it takes too long in CI
  pull_request:
    branches:
      - main
  #   paths:
  #     - 'Makefile'
  #     - 'pyproject.toml'
  #     - 'src/olmo_core/version.py'
  #     - 'src/Dockerfile'
  #     - '.github/workflows/docker.yml'
  push:
    # branches:
    #   - main
    tags:
      - 'v*.*.*'

jobs:
  docker:
    name: CUDA ${{ matrix.cuda }} ${{ matrix.target }}
    runs-on: ubuntu-latest-m
    timeout-minutes: 60
    env:
      BEAKER_TOKEN: ${{ secrets.BEAKER_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        cuda: ["12.4", "12.6"]
        target: ["stable", "nightly", "stable-dev", "nightly-dev"]
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Beaker
        uses: allenai/setup-beaker@v2
        if: env.BEAKER_TOKEN != ''
        with:
          token: ${{ env.BEAKER_TOKEN }}
          workspace: ${{ env.BEAKER_WORKSPACE }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set env vars
        run: |
          echo "BEAKER_WORKSPACE=$(make get-beaker-workspace)" >> $GITHUB_ENV
          #rm -rf /opt/hostedtoolcache  # clear up some disk space

      - name: Build image
        run: |
          make ${{ matrix.target }}-image CUDA_VERSION=${{ matrix.cuda }}

      - name: Push to GHCR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          make ghcr-image-${{ matrix.target }} CUDA_VERSION=${{ matrix.cuda }}

      - name: Push to Beaker
        if: env.BEAKER_TOKEN != '' && startsWith(github.ref, 'refs/tags/')
        run: |
          make beaker-image-${{ matrix.target }} CUDA_VERSION=${{ matrix.cuda }}
