name: Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  beaker:
    name: Beaker image (${{ matrix.build.version }})
    runs-on: ${{ matrix.build.runs-on }}
    timeout-minutes: 60
    env:
      BEAKER_TOKEN: ${{ secrets.BEAKER_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - version: stable
            runs-on: ubuntu-latest

          - version: nightly
            runs-on: ubuntu-latest

          - version: dev
            runs-on: ubuntu-latest-m  # requires a larger instance
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Set env vars
        run: |
          echo "BEAKER_WORKSPACE=$(make get-beaker-workspace)" >> $GITHUB_ENV

      - name: Build
        run: |
          make ${{ matrix.build.version }}-image

      - uses: allenai/setup-beaker@v2
        if: env.BEAKER_TOKEN != ''
        with:
          token: ${{ env.BEAKER_TOKEN }}
          workspace: ${{ env.BEAKER_WORKSPACE }}

      - name: Push
        if: env.BEAKER_TOKEN != '' && startsWith(github.ref, 'refs/tags/')
        run: |
          rm -rf /opt/hostedtoolcache  # clear up some disk space
          make beaker-image-${{ matrix.build.version }}
